name: Cypress Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  run-cypress:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: ğŸŸ¢ Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: ğŸ“¦ Instalar dependÃªncias
        working-directory: ./teste_outsera/testeCypress/cypress
        run: npm install

      - name: ğŸš€ Executar testes Cypress
        working-directory: ./teste_outsera/testeCypress/cypress
        run: |
          npx cypress run

      - name: ğŸ“ Upload de screenshots (se houver falhas)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: testeCypress/cypress/screenshots/

      - name: ğŸ“ Upload de vÃ­deos (opcional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos
          path: testeCypress/cypress/videos/

      - name: ğŸ“ Upload de relatÃ³rios HTML (caso gerados)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: testeCypress/cypress/reports/
